# Generated by Django 4.1.2 on 2022-10-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='doc_image',
            field=models.ImageField(upload_to='doctor_image'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_spec', models.CharField(max_length=11)),
                ('p_mail', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doc')),
            ],
        ),
    ]
