# Generated by Django 4.1.2 on 2022-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doc_doc_image_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='p_mail',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='p_spec',
        ),
        migrations.AddField(
            model_name='booking',
            name='p_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='p_phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
